[package]
name        = "weigong-bridge"
description = "Bridge napi-rs: Expose the rust engine to Node"
version.workspace  = true
edition.workspace  = true
authors.workspace  = true
license.workspace  = true

[lib]
crate-type = ["cdylib"]

[dependencies]
weigong-engine = { path = "../engine" }
napi           = { version = "2", features = ["napi8"] }
napi-derive    = "2"
anyhow         = { workspace = true }

[build-dependencies]
napi-build = "2"

[profile.release]
opt-level     = 3
lto           = "fat"
codegen-units = 1
panic         = "abort"
strip         = true