[package]
name        = "weigong-selfplay"
description = "Masive selfplay + NNUE training with OpenCL for Weigong"
version.workspace  = true
edition.workspace  = true
authors.workspace  = true
license.workspace  = true

[dependencies]
weigong-engine = { path = "../engine" }
anyhow         = { workspace = true }
thiserror      = { workspace = true }
log            = { workspace = true }
env_logger     = { workspace = true }
bytemuck       = { workspace = true }
memmap2        = { workspace = true }
opencl3        = { workspace = true }
rayon          = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }

[[bin]]
name = "selfplay"
path = "src/main.rs"